### ISSUE TITLE
Implement Construction Payload Request

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-mirror-node#43]
- We should be able to construct transactions

**Comment by Perseverance** [comment]
The request will contain at least two operations - one indicating how much sender has sent (indicated by negative amount) and how much the receiver(s) will receive (indicated by positive amount)

**Comment by Perseverance** [comment]
Use the research in #45 to figure out how to do it with the Hedera Go SDK
