### ISSUE TITLE
Research Hedera Go SDK Creation of Unsigned TX

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-mirror-node#45]

**Comment by Perseverance** [comment]
https://github.com/hashgraph/hedera-sdk-go/blob/0d1c09db506495fac27bb745ec43efb0bd0fb872/examples/create_account_with_manual_signing/main.go#L32

Transaction builders in Hedera GO SDK have a `Build` Method. It returns `Transaction` Object that has a `MarshalBinary` method that returns []byte unsigned transaction bytes. We can use `encoding/hex` to encode the bytes to hex.

Similarly, we can take hex-encoded Transaction binary, decode it to []byte and use the `UnmarshalBinary` method of Transaction object to populate it with the decoded bytes.

**Comment by Perseverance** [comment]
Almost working code:
```
client = hedera.ClientForTestnet()
t, err := hedera.NewCryptoTransferTransaction().
		AddSender(operatorAccountID, hedera.NewHbar(100)). // Accounts with negative amount are senders
		AddRecipient(newAccountID, hedera.NewHbar(100)). // Accounts with positive amount are recepients
		AddRecipient(newAccountID2, hedera.NewHbar(300)). 
		Build(client)

	bt, err := t.MarshalBinary()
	tStr := hex.EncodeToString(bt)
	fmt.Println(tStr)
```

**Comment by Perseverance** [comment]
Parsing it back:
```
utb, err := hex.DecodeString(tStr)
	var uT hedera.Transaction
	uT.UnmarshalBinary(utb)
```
